### ISSUE TITLE
Acoplamiento entre espejo y Rolando

### ISSUE THREAD

**Issue by sanuzzi** [karengrams/PdPGrupo16#33]
Fíjense que el espejo tiene dueño. O sea que si Rolando tiene un espejo, y este espejo tiene un dueño.

Si Rolando usa un espejo, hay que validar que el espejo tenga por dueño a Rolando. Y si Rolando deja de usar al espejo, éste debe dejar de tenerlo como dueño.

¿Se ve que mantener esa consistencia es bastante costosa?

También hay otro problema: El espejo se podría usar para únicamente un personaje. Jamás para 2 a la vez.

Ambos problemas, se solucionarían si el espejo no se guardara al dueño. Directamente, cuando quieren saber cuánto aporta, se le puede pasar al personaje que la use en ese instante.

Internamete hace su cálculo, devuelve la info, y listo, no necesita guardarse nada. ¿Se ve?

Lo mismo aplica a otras entidades: La bendicion, por ejemplo, ni siquiera se lo guarda en una referencia sino que tiene cableado el WKO en el código. Jamás podría usarse para otro personaje.

Estos cambios van a repercutir en los otros objetos también para tratarlos de forma polimórfica. Es importante que verifiquen que todos los tests queden andando bien luego de este cambio.

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/artefactos.wlk#L42-L57
