### ISSUE TITLE
El espejo rompe el encapsulamiento de Rolando

### ISSUE THREAD

**Issue by sanuzzi** [karengrams/PdPGrupo16#34]
El espejo agarra la colección de Rolando y la revuelve a su beneficio.

¿Y si Rolando se encarga un poco más de saber revolver sus cosas?

Es un punto complicado, es difícil un buen balance de responsabilidades, pero intenten darle una vuelta de tuerca y que Rolando **encapsule** el comportamiento para manipular **sus** cosas.

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/artefactos.wlk#L42-L57
