### ISSUE TITLE
Properties innecesarias en personaje

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#35]
- baseDeHechiceria si bien lo definieron como constante, es un valor que no va a cambiar de personaje a personaje, por ende, nos conviene dejarlo como un metodo que devuelva directamente el valor (3)

-nivelDeHechiceria, nivelDeLucha no los estan usando para nada, y esta bien, por que no son necesarios jajaja. Ya definieron dos métodos que hacen el calculo que corresponde y devuelve el resultado, suficiente.

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/Personaje.wlk#L14
