### ISSUE TITLE
es poderoso hechizoBasico??

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#36]
Aca pasa lo mismo que con personaje.
Por definición el hechizo básico no es poderoso... Entonces simplemente armemos un metodo que devuelva si es poderoso o no.

Y les digo mas, fijense que en Logo ustedes modelaron sosPoderoso como un metodo... Los dos son hechizos, por lo que deberían entender el mismo mensaje. (En este caso entiende el mismo mensaje, pero por que hicimos uso y abuso del getter que nos regalo property jaja)

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/794726ea3d075d89e5ad05c50fd8a3b1b463f53b/TPObjetos2018/src/hechizos.wlk#L21
