### ISSUE TITLE
Clase Artefacto

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#37]
Esta bien esta herencia, había que hacerla, pero estan definiendo dos properties que en las clases hijas definen como métodos.

No me parece mal que lo definan en Artefacto, pero en vez de clavar las properties, las definiría como métodos abstractos.

**Comment by miguelshevchuk** [comment]
En mascara me hicieron trampa!! El enunciado no indica como se calcula el valor de la mascara, pero aun asi, para no romper con el polimorfismo, lo deberíamos definir nosotros.

Ustedes lo pusieron con valor 0, lo cual esta bien, pero esta definido como property en la clase Artefacto!!!! 

Hagan eso mismo, pero el valor de la mascara, defínanlo en la mascara...

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/794726ea3d075d89e5ad05c50fd8a3b1b463f53b/TPObjetos2018/src/artefactos.wlk#L7-L10
