### ISSUE TITLE
Valor de la armadura

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#40]
Ustedes ahi definen que el calculo del valor de la armadura, siempre es sumar el valor de base de la armadura, mas algo mas.
El enunciado no indica eso, ese calculo solamente funciona para la bendición.

Entonces, adentro del metodo "valor" de bendición, tienen que buscar la manera de sumarle el valor de base de la armadura...

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/artefactos.wlk#L63
