### ISSUE TITLE
unidadDeLucha en Armadura

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#41]
En los refuerzos no definen el metodo "unidadDeLucha", sino que nuevamente lo definen como property en una clase padre.

Por otro lado, en bendición definen un constructor en donde clavan un "bendecido" en una property, y despues lo usan para calcular la unidadDeLucha.
En realidad no es una buena practica hacer esto. Suponganse que quieren usar el mismo refuerzo para dos armaduras distintas. Esta solución que implementan, los obliga a instanciar dos veces el refuerzo con un "bendecido" diferente.

Recuerden que es posible pasar por parametro al mismo objeto que estan usando, mediante Self

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/artefactos.wlk#L71-L93

https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/artefactos.wlk#L59-L67
