### ISSUE TITLE
Punto 3 - Espejos y libro de hechizos

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#42]
Falta contestar:
ESPEJO Y LIBRO DE HECHIZOS
Su comportamiento es el mismo. Simplemente, ahora son muchos los personajes pueden contar con espejos o libros de hechizos entre sus pertenencias. 
Para pensar:
¿Es necesario, conveniente o indistinto que haya muchos espejos y libros de hechizos o que sigan siendo únicos? 
Replantearse la pregunta de la primer entrega acerca de la posibilidad de un libro de hechizo que tenga entre sus hechizos un libro de hechizos.

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/artefactos.wlk#L38-L40

https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/hechizos.wlk#L28-L34
