### ISSUE TITLE
Validacion de costeo en la compra

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#43]
Con la solución que ustedes implementan, el usuario nunca se entera si hubo un error al comprar el hechizo/artefacto.

Deberían avisarle de alguna manera que no tiene plata para comprar el hechizo/artefacto. 

Para ayudarles, la herramienta que tienen que usar empieza con E, y termina con xcepciones.

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/5d6c34297beaf060735523b6802c1a17f86ac1c4/TPObjetos2018/src/Personaje.wlk#L44-L47

https://github.com/karengrams/PdPGrupo16/blob/5d6c34297beaf060735523b6802c1a17f86ac1c4/TPObjetos2018/src/Personaje.wlk#L44-L47
