### ISSUE TITLE
Test 5  hechicería 

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#45]
No hace falta volver a cambiar el nombre. Recuerden que lo que pasa en cada test, muere ahi y los cambios realizados no se ven reflejados en los tests siguientes

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/testdehechiceria.wtest#L11-L13
