### ISSUE TITLE
Test 6 Lucha reformulada

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#47]
Aca estan obligados a poner la base en 0 para que de bien el test, y en la consigna nunca pide que ese valor sea 0.

Revisen su código y fijense como pueden solucionarlo. Ya lo marcamos en otro issue

**Comment by miguelshevchuk** [comment]
en el test 7 paso lo mismo

**Comment by miguelshevchuk** [comment]
Y en realidad el TEST, pregunta por el valor de lucha **de la mascara** y ustedes estan calculando el valor de lucha de Rolando..

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e8329f45052a7776027a67fb35de379c2ddb2aab/TPObjetos2018/src/testdeluchareformulada.wtest#L55-L63
