### ISSUE TITLE
Test 5 Comercio

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#49]
Aca estan verificando las monedas del tipo, y no si pudo comprar el hechizo...

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/5d6c34297beaf060735523b6802c1a17f86ac1c4/TPObjetos2018/src/testdecomercio.wtest#L49-L52

https://github.com/karengrams/PdPGrupo16/blob/5d6c34297beaf060735523b6802c1a17f86ac1c4/TPObjetos2018/src/testdecomercio.wtest#L70-L73
