### ISSUE TITLE
Mejoras en la compra de cosas

### ISSUE THREAD

**Issue by miguelshevchuk** [karengrams/PdPGrupo16#50]
Para hacer un poco mas prolija la compra, tratemos de hacer que el metodo "compra" pueda recibir un artefacto o un hechizo.
Para lograr esto:

1- Hacer que el artefacto / hechizo sepa cuanto tiene que gastar cierto personaje para comprarlo
2- Definir un metodo "compra" que reciba un "elemento comprable"
3- Hacer que este metodo reste a las monedas del personaje, el valor de compra del elemento comprable (Con las validaciones que correspondan)
4- No tenemos que usar IFS para saber si es un artefacto o un hechizo!!!. Sabiendo eso, fíjense como hacen para que **_el elemento comprable se agregue_** al personaje.

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/5d6c34297beaf060735523b6802c1a17f86ac1c4/TPObjetos2018/src/Personaje.wlk#L55-L63
