### ISSUE TITLE
Aprovechar polimorfismo en condicion de compra

### ISSUE THREAD

**Issue by MarianoSalerno** [karengrams/PdPGrupo16#54]
Deleguen el descuento en cada hechizo/artefacto

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e881b146f754c55bd7cacf179c19a6239500c697/TPObjetos2018/src/Personaje.wlk#L47-L52

https://github.com/karengrams/PdPGrupo16/blob/e881b146f754c55bd7cacf179c19a6239500c697/TPObjetos2018/src/Personaje.wlk#L54

https://github.com/karengrams/PdPGrupo16/blob/e881b146f754c55bd7cacf179c19a6239500c697/TPObjetos2018/src/hechizos.wlk#L5

https://github.com/karengrams/PdPGrupo16/blob/e881b146f754c55bd7cacf179c19a6239500c697/TPObjetos2018/src/artefactos.wlk#L11
