### ISSUE TITLE
Borrar el metodo comprar con 1 solo parametro

### ISSUE THREAD

**Issue by MarianoSalerno** [karengrams/PdPGrupo16#56]
En los tests usar un comerciante cualquiera. Simplificar todo lo que corresponda con este cambio

**Comment by karengrams** [comment]
https://github.com/karengrams/PdPGrupo16/blob/e881b146f754c55bd7cacf179c19a6239500c697/TPObjetos2018/src/Personaje.wlk#L47-L52
